# myapi/urls.py
from django.urls import include, path
from rest_framework import routers
from myapi.views.api.v1.property_views import PropertyListView, PropertyDetailView
from myapi.views.api.v1.seller.property_views import (
    PropertyListView as SellerPropertyListView,
    PropertyDetailView as SellerPropertyDetailView,
)
from myapi.views.api.v1.lobstr.leboncoin.external_property_views import (
    ExternalPropertyListView as LeboncoinExternalPropertyListView,
)
from myapi.views.api.v1.user.user_external_property_views import (
    UserExternalPropertyViewSet,
)

router = routers.DefaultRouter()
router.register(
    r"user/user_external_properties",
    UserExternalPropertyViewSet,
    basename="user_external_property",
)

urlpatterns = [
    path(
        "api/v1/properties",
        PropertyListView.as_view(),
        name="api_v1_seller_property-detail",
    ),
    path(
        "api/v1/properties/<int:property_id>",
        PropertyDetailView.as_view(),
        name="api_v1_property-detail",
    ),
    path(
        "api/v1/seller/<int:seller_id>/properties",
        SellerPropertyListView.as_view(),
        name="api_v1_seller_property-list",
    ),
    path(
        "api/v1/seller/<int:seller_id>/properties/<int:property_id>",
        SellerPropertyDetailView.as_view(),
        name="api_v1_seller_property-detail",
    ),
    path(
        "api/v1/lobstr/leboncoin/external_properties/",
        LeboncoinExternalPropertyListView.as_view(),
        name="api_v1_lobstr_leboncoin_external-properties-list",
    ),
    path(
        "api/v1/", include(router.urls)
    ),  # This includes the URLs generated by the DefaultRouter
]
