# Generated by Django 4.2.3 on 2023-07-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_hero_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='alias',
        ),
    ]
