# Generated by Django 4.2.3 on 2023-08-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0003_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
