# Generated by Django 4.2.3 on 2023-07-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_remove_hero_alias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hero',
            new_name='Property',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='title',
        ),
    ]
