# Generated by Django 4.2.3 on 2023-07-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_rename_hero_property_rename_name_property_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Property',
        ),
    ]
