# Generated by Django 4.2.3 on 2023-08-16 08:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0004_customuser_is_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserExternalProperty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("contacted", "Contacted"),
                            ("rejected", "Rejected"),
                            ("waiting", "Waiting"),
                        ],
                        default="waiting",
                        max_length=10,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "external_property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapi.externalproperty",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "external_property")},
            },
        ),
    ]
