# Generated by Django 4.2.3 on 2023-08-19 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0005_userexternalproperty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalproperty",
            name="nb_rooms",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="externalproperty",
            name="source_id",
            field=models.CharField(
                default="",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
    ]
