# Generated by Django 4.2.3 on 2023-07-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("myapi", "0005_delete_property"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=60)),
                ("city", models.CharField(max_length=150)),
            ],
        ),
    ]
