# Generated by Django 4.2.3 on 2023-07-06 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0007_property_surface_alter_property_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="address",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="country",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="postal_code",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="surface",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100000),
                ],
            ),
        ),
    ]
