# Generated by Django 4.2.3 on 2023-08-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0007_customuser_created_at_customuser_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="externalproperty",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="photo",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="seller",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userexternalproperty",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
