# Generated by Django 4.2.3 on 2023-07-09 08:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0008_property_address_property_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "civility",
                    models.CharField(
                        choices=[
                            ("mr", "Mr"),
                            ("mrs", "Mrs"),
                            ("unspecified", "Unspecified"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=30,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=30,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="property",
            name="seller",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="properties",
                to="myapi.seller",
            ),
        ),
    ]
