# Generated by Django 4.2.3 on 2023-08-22 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0008_alter_customuser_updated_at_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Property",
        ),
        migrations.DeleteModel(
            name="Seller",
        ),
    ]
