# Generated by Django 4.2.3 on 2023-07-28 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0009_seller_property_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="first_name",
            field=models.CharField(
                max_length=50, validators=[django.core.validators.MinLengthValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="last_name",
            field=models.CharField(
                max_length=50, validators=[django.core.validators.MinLengthValidator(1)]
            ),
        ),
    ]
