# Generated by Django 4.2.3 on 2023-08-23 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0009_delete_property_delete_seller"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalproperty",
            name="elevator",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="externalproperty",
            name="property_type",
            field=models.CharField(
                choices=[("Appartement", "Appartement"), ("House", "House")],
                default="Appartement",
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="externalproperty",
            name="region",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="externalproperty",
            name="source",
            field=models.CharField(
                choices=[("Leboncoin", "Leboncoin"), ("pap", "PAP")],
                default="Leboncoin",
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
    ]
