# Generated by Django 4.2.3 on 2023-08-23 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0011_alter_externalproperty_nb_parkings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalproperty",
            name="first_photo_url",
            field=models.CharField(
                blank=True,
                default="",
                null=True,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
    ]
