# Generated by Django 4.2.3 on 2023-07-28 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0011_externalproperty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalproperty",
            name="currency",
            field=models.CharField(
                choices=[("EUR", "Euro"), ("USD", "US Dollar")],
                max_length=3,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="externalproperty",
            name="url",
            field=models.CharField(
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.URLValidator(),
                ]
            ),
        ),
    ]
