# Generated by Django 4.2.3 on 2023-07-28 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0012_alter_externalproperty_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalproperty",
            name="energy_rate",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="externalproperty",
            name="first_photo_url",
            field=models.CharField(
                default="",
                max_length=200,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.URLValidator(),
                ],
            ),
        ),
        migrations.AddField(
            model_name="externalproperty",
            name="gps_latitude",
            field=models.CharField(
                default="",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="externalproperty",
            name="gps_longitude",
            field=models.CharField(
                default="",
                max_length=100,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AddField(
            model_name="externalproperty",
            name="outside_access",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="externalproperty",
            name="source_id",
            field=models.CharField(
                default="",
                max_length=100,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
    ]
