# Generated by Django 4.2.3 on 2023-08-23 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0012_alter_externalproperty_first_photo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalproperty",
            name="nb_rooms",
            field=models.IntegerField(
                blank=True,
                default=1,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
