# Generated by Django 4.2.3 on 2023-07-28 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0013_externalproperty_energy_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        validators=[
                            django.core.validators.MinLengthValidator(1),
                            django.core.validators.URLValidator(),
                        ]
                    ),
                ),
            ],
        ),
    ]
