# Generated by Django 4.2.3 on 2023-08-24 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0014_alter_externalproperty_nb_rooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalproperty",
            name="source_id",
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
    ]
