# Generated by Django 4.2.3 on 2023-07-28 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0014_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="external_property",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="external_properties",
                to="myapi.externalproperty",
            ),
        ),
    ]
