# Generated by Django 4.2.3 on 2023-07-31 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0015_photo_external_property"),
    ]

    operations = [
        migrations.RenameField(
            model_name="externalproperty",
            old_name="immo_type",
            new_name="property_type",
        ),
        migrations.RemoveField(
            model_name="externalproperty",
            name="has_phone",
        ),
        migrations.RemoveField(
            model_name="externalproperty",
            name="kind",
        ),
        migrations.AlterField(
            model_name="externalproperty",
            name="floor_number",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="externalproperty",
            name="nb_floors_building",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="externalproperty",
            name="outside_access",
            field=models.CharField(blank=True, null=True),
        ),
    ]
