# Generated by Django 4.2.3 on 2023-07-31 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0016_rename_immo_type_externalproperty_property_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalproperty",
            name="first_photo_url",
            field=models.CharField(
                default="",
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.URLValidator(),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="externalproperty",
            name="floor_number",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="externalproperty",
            name="nb_floors_building",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100000),
                ],
            ),
        ),
    ]
