# Generated by Django 4.2.3 on 2023-08-24 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0016_alter_externalproperty_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalproperty",
            name="source",
            field=models.CharField(
                choices=[("leboncoin", "Leboncoin"), ("pap", "PAP")],
                default="leboncoin",
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
    ]
