# Generated by Django 4.2.3 on 2023-07-31 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0017_alter_externalproperty_first_photo_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalproperty",
            name="nb_parkings",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100000),
                ],
            ),
        ),
    ]
