# Generated by Django 4.2.3 on 2023-07-31 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0018_alter_externalproperty_nb_parkings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="position",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
    ]
