# Generated by Django 4.2.3 on 2023-08-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0020_alter_externalproperty_energy_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalproperty",
            name="phone",
            field=models.CharField(null=True),
        ),
    ]
