# Generated by Django 4.2.3 on 2023-08-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0021_externalproperty_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalproperty",
            name="phone",
            field=models.CharField(blank=True, null=True),
        ),
    ]
