# Generated by Django 4.2.3 on 2023-08-01 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0022_alter_externalproperty_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="externalproperty",
            old_name="phone",
            new_name="seller_email",
        ),
        migrations.AddField(
            model_name="externalproperty",
            name="nb_bedrooms",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="externalproperty",
            name="price",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="externalproperty",
            name="seller_name",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="externalproperty",
            name="seller_phone",
            field=models.CharField(blank=True, null=True),
        ),
    ]
