# Generated by Django 4.2.3 on 2023-08-01 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0023_rename_phone_externalproperty_seller_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalproperty",
            name="nb_bedrooms",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
