# Generated by Django 4.2.3 on 2023-08-01 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0024_alter_externalproperty_nb_bedrooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalproperty",
            name="property_type",
            field=models.CharField(
                choices=[("Appartement", "Appartement"), ("House", "House")],
                default="Appartment",
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
    ]
