# Generated by Django 4.2.3 on 2023-08-14 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("myapi", "0025_alter_externalproperty_property_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="external_property",
        ),
        migrations.AddField(
            model_name="photo",
            name="content_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="photo",
            name="object_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
